general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

listener {
    timeout = 500       # 5 min - lock screen
    on-timeout = hyprlock
}

listener {
    timeout = 600       # 10 min - turn off displays
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    event = lid
    on-close = hyprlock
}

listener {
    event = before-sleep
    on-event = hyprlock
}
