-- Minimal Neovim config (0.12+): lazy.nvim, snacks, mini.base16 (matugen), treesitter, native LSP.
-- Language servers, tree-sitter CLI and gcc come from PATH (install via Nix), not Mason.
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Options
vim.o.number = true
vim.o.relativenumber = true
vim.o.signcolumn = "yes"
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.undofile = true
vim.o.clipboard = "unnamedplus"
vim.o.expandtab = true
vim.o.shiftwidth = 2
vim.o.tabstop = 2
vim.o.termguicolors = true
vim.o.showmode = false

-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable",
    "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  -- Colorscheme engine; the actual palette is generated by matugen (see Theme below)
  { "echasnovski/mini.base16", lazy = false, priority = 1000 },
  { "echasnovski/mini.statusline", opts = {} },
  {
    "saghen/blink.cmp",
    version = "1.*", -- downloads a prebuilt fuzzy-matcher binary
    dependencies = { "rafamadriz/friendly-snippets" },
    lazy = false,
    opts = {
      keymap = { preset = "enter" }, -- same as LazyVim: <CR> accepts
      completion = {
        documentation = { auto_show = true, auto_show_delay_ms = 200 },
        ghost_text = { enabled = true },
      },
      sources = { default = { "lsp", "path", "snippets", "buffer" } },
      fuzzy = { implementation = "prefer_rust_with_warning" },
    },
  },
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "main",
    lazy = false,         -- doesn't support lazy-loading
    build = ":TSUpdate",  -- update parsers when the plugin updates
    config = function()
      -- Already-installed parsers are skipped; add languages here as needed
      require("nvim-treesitter").install({
        "c", "cpp", "lua", "nix", "qmljs",
        "html", "css", "javascript",
        "bash", "json", "markdown", "markdown_inline", "go",
      })

      -- Enable treesitter highlighting + indent for any buffer that has a parser
      vim.api.nvim_create_autocmd("FileType", {
        callback = function(ev)
          if pcall(vim.treesitter.start, ev.buf) then
            vim.bo[ev.buf].indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
          end
        end,
      })
    end,
  },

  {
    "windwp/nvim-autopairs",
    event = "InsertEnter",
    config = function()
      local npairs = require("nvim-autopairs")
      local Rule = require("nvim-autopairs.rule")
      local cond = require("nvim-autopairs.conds")

      npairs.setup({ check_ts = true }) -- don't pair inside strings/comments

      -- Pair <> only after an identifier (std::vector<, Foo<), not in `a < b`
      npairs.add_rule(
        Rule("<", ">")
          :with_pair(cond.before_regex("%a+:?:?$", 3))
          :with_move(function(opts) return opts.char == ">" end)
      )
    end,
  },

  {
    "folke/snacks.nvim",
    priority = 1000,
    lazy = false,
    opts = {
      explorer = { enabled = true },
      picker = { enabled = true },
    },
    keys = {
      { "<leader>e", function() Snacks.explorer() end, desc = "Explorer" },
      { "<leader>/", function() Snacks.picker.grep() end, desc = "Grep" },
      { "<leader><space>", function() Snacks.picker.files() end, desc = "Find files" },
    },
  },

  -- Only provides server definitions (cmd, filetypes, root markers); installs nothing.
  { "neovim/nvim-lspconfig" },
  { "olrtg/nvim-emmet", ft = { "html", "css" } },
}, {
  checker = { enabled = false },
})

-- Theme: matugen writes colors/matugen.lua and sends SIGUSR1 on wallpaper change
local function load_theme()
  if not pcall(vim.cmd.colorscheme, "matugen") then return end
  local bg = vim.api.nvim_get_hl(0, { name = "Normal" }).bg
  for _, group in ipairs({ "LineNr", "LineNrAbove", "LineNrBelow", "CursorLineNr", "SignColumn", "FoldColumn" }) do
    vim.api.nvim_set_hl(0, group, vim.tbl_extend("force", vim.api.nvim_get_hl(0, { name = group }), { bg = bg }))
  end
end
load_theme()
vim.api.nvim_create_autocmd("Signal", {
  pattern = "SIGUSR1",
  callback = function()
    load_theme()
    vim.cmd.redraw()
  end,
})

-- LSP
vim.lsp.config("lua_ls", {
  settings = { Lua = { diagnostics = { globals = { "vim", "Snacks" } } } },
})
vim.lsp.config("qmlls", { cmd = { "qmlls", "-E" } })
vim.lsp.enable({ "clangd", "lua_ls", "emmet_language_server", "qmlls", "gopls" })

vim.diagnostic.config({ virtual_text = true })
-- Built-in LSP keys: K hover, grn rename, gra code action, grr references,
-- gri implementation, Ctrl-] definition, [d / ]d diagnostics. See :help lsp-defaults
vim.keymap.set("n", "<leader>cf", vim.lsp.buf.format, { desc = "Format buffer" })

-- Your HTML dev server (lua/devserver.lua)
require("devserver")
